/**
 * lib/evergreen-seeds.ts
 *
 * Client-curated evergreen blog post ideas for Shana's content engine.
 * These are guide-style / explainer pieces — not news. They give the VA
 * picker a rich menu to choose from beyond daily Tavily news + history.
 *
 * Differences from history-seeds.ts:
 *  - Stable slug-based IDs (no weekId suffix). Once Shana picks an idea,
 *    it's marked approved and never re-appears — the menu naturally shrinks
 *    as content is produced.
 *  - researchData is a short directional brief; the writer fills gaps
 *    with Tavily research at write time.
 *  - Mixed categories (community, market-update, investor-tips, local-history,
 *    seller-tips, trending-topics) to ensure variety in the picker.
 */

import type { IdeaCandidate, ArticleCategory, IdeaAudience } from './types'
import { saveIdea, getIdea } from './idea-store'

interface EvergreenSeed {
  slug: string
  title: string
  category: ArticleCategory
  city: string
  audiences: IdeaAudience[]
  contentType: string
  targetKeyword: string
  angle: string
  whyItMatters: string
  researchData: string
}

// ── Palm Springs neighborhood & lifestyle guides ─────────────────────────
const PALM_SPRINGS_LIFESTYLE: EvergreenSeed[] = [
  {
    slug: 'best-palm-springs-neighborhoods-by-lifestyle',
    title: 'The Best Neighborhoods in Palm Springs for Every Lifestyle',
    category: 'community',
    city: 'Palm Springs',
    audiences: ['buyer', 'local'],
    contentType: 'Community',
    targetKeyword: 'best Palm Springs neighborhoods',
    angle: "A neighborhood-by-neighborhood breakdown matching buyer profiles to the right Palm Springs zip code — from Old Las Palmas glamour to Sunrise Park family-friendly to Movie Colony nightlife.",
    whyItMatters: "Most buyers Google a city, not a neighborhood. Helping them narrow from 'Palm Springs' down to the specific area that fits their lifestyle is one of the most useful services Shana can offer — and it builds long-term SEO authority for every Palm Springs neighborhood term.",
    researchData: "Cover: Old Las Palmas (luxury, celebrity history), Movie Colony (mid-century modern, walkable), Sunrise Park (family/affordable), Vista Las Palmas, Andreas Hills (golf), Indian Canyons (lifestyle/mountain views), Tahquitz River Estates, Deepwell Estates, Mesa, The Mesa. For each: median home price band, walkability, vibe, who it fits, signature architecture. Pull current MLS price ranges from search.searchcoachellavalleyhomes.com.",
  },
  {
    slug: 'living-in-palm-springs-pros-cons',
    title: 'Living in Palm Springs: Pros and Cons for New Residents',
    category: 'community',
    city: 'Palm Springs',
    audiences: ['buyer', 'local'],
    contentType: 'Community',
    targetKeyword: 'living in Palm Springs pros cons',
    angle: "An honest look at desert living from someone who chose it — what new residents love, what surprises them, and what they wish they knew before they moved.",
    whyItMatters: "Buyers researching a relocation specifically search 'pros and cons' content. Writing it from a local's POV builds trust faster than a generic listicle and positions Shana as the agent who tells the truth.",
    researchData: "Pros: 350+ sun days, low humidity, world-class hiking, mid-century architecture, festival economy (Coachella, Modernism Week), no state income tax for retirees from neighboring states. Cons: 110-120°F summer heat, monsoon flash floods, distance from coastal beaches (~2hr to LA), some HOAs strict, peak-season traffic. Include practical advice on summer adaptation and snowbird timing.",
  },
  {
    slug: 'locals-guide-palm-springs-neighborhoods',
    title: "A Local's Guide to Palm Springs Neighborhoods",
    category: 'community',
    city: 'Palm Springs',
    audiences: ['buyer', 'local'],
    contentType: 'Community',
    targetKeyword: 'Palm Springs neighborhoods guide local',
    angle: "The kind of neighborhood tour you'd give a friend in town for the weekend — not from a brochure but from someone who actually lives here and knows where to eat, walk, and watch the sunset.",
    whyItMatters: "Local-voice content outperforms generic real estate copy 5:1 on engagement. This is the article that gets bookmarked and shared.",
    researchData: "Conversational tour through neighborhoods. Include: walking routes, best taco spot, best coffee, where locals avoid in peak season, hidden mid-century gems, where to catch live music. Tone: warm, knowing, never sales-y.",
  },
  {
    slug: 'palm-springs-vs-other-desert-cities',
    title: 'What Makes Palm Springs Different from Other Desert Cities?',
    category: 'community',
    city: 'Palm Springs',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'Palm Springs vs other desert cities comparison',
    angle: "Why buyers choose Palm Springs over Scottsdale, Las Vegas, Santa Fe, or Tucson — the architectural concentration, the Hollywood legacy, the climate quirks, the cultural identity.",
    whyItMatters: "Decision-stage buyers comparing destinations need this. Honest comparison content earns links and citations from relocation forums.",
    researchData: "Compare on: architecture density, year-round climate, distance to major coastal cities (LA, SD), cultural calendar (Coachella, Modernism Week, film festival), property tax burden, food scene maturity, LGBTQ-friendliness. Don't just praise PS — call out where Scottsdale or Tucson actually win (e.g. summer livability).",
  },
  {
    slug: 'cost-of-living-palm-springs',
    title: 'The Cost of Living in Palm Springs: What to Expect',
    category: 'market-update',
    city: 'Palm Springs',
    audiences: ['buyer', 'homeowner'],
    contentType: 'Market Update',
    targetKeyword: 'cost of living Palm Springs California',
    angle: "Real numbers — housing, utilities, groceries, healthcare, taxes — for someone considering relocating to Palm Springs in 2026.",
    whyItMatters: "Cost-of-living posts are searched constantly by remote workers and retirees considering Palm Springs. Accurate, current figures win the SEO and the trust.",
    researchData: "Pull current data: median home price, average rent (1BR/2BR), utility costs (note: summer AC bills can hit $400+/mo), water rates via CVWD, grocery index, gas, CA state income tax bracket, sales tax. Compare against national median and LA/SD/SF metros.",
  },
  {
    slug: 'top-outdoor-activities-palm-springs',
    title: 'Top Outdoor Activities for Palm Springs Residents',
    category: 'community',
    city: 'Palm Springs',
    audiences: ['local', 'buyer'],
    contentType: 'Community',
    targetKeyword: 'Palm Springs outdoor activities residents',
    angle: "Beyond the obvious hike-and-pool list — what locals actually do outdoors when the weather cooperates, season by season.",
    whyItMatters: "Lifestyle content drives organic search and shows buyers what their weekends could look like. Strong evergreen.",
    researchData: "Cover: Indian Canyons hiking, Aerial Tramway (Mt San Jacinto), Lykken Trail, Bump and Grind, golf at PGA West, Joshua Tree day trips, Salton Sea drives, El Paseo strolls, farmers markets, pickleball at DeMuth Park, e-bike Tahquitz Canyon. Note seasonal limits (avoid hiking 11am-4pm May-Sep).",
  },
  {
    slug: 'palm-springs-luxury-real-estate-origins',
    title: 'How Palm Springs Became a Luxury Real Estate Destination',
    category: 'local-history',
    city: 'Palm Springs',
    audiences: ['buyer', 'local'],
    contentType: 'Local History',
    targetKeyword: 'Palm Springs luxury real estate history',
    angle: "The 1920s-1960s arc that turned a dusty desert outpost into the playground of presidents, studio heads, and the global design elite.",
    whyItMatters: "Buyers at the luxury end specifically want to know they're buying into a legacy market, not a marketing fad. Telling the story sells the market.",
    researchData: "Cover: 1920s Hollywood discovery of the desert, the '2-hour rule' for studio contracts keeping stars close to LA, El Mirador Hotel (1928), Racquet Club (1934), Albert Frey's early commissions, the 1947 commission boom, Modernism Week origin (2006), Kaufmann Desert House $25M sale (2022). Tie history → current price premiums.",
  },
]

// ── Buyer & investor guides ──────────────────────────────────────────────
const BUYER_INVESTOR_GUIDES: EvergreenSeed[] = [
  {
    slug: 'first-time-homebuyer-palm-springs',
    title: "First-Time Homebuyer's Guide to Palm Springs",
    category: 'market-update',
    city: 'Palm Springs',
    audiences: ['buyer'],
    contentType: 'Market Update',
    targetKeyword: 'first time home buyer Palm Springs guide',
    angle: "Everything a first-time buyer needs to navigate the Palm Springs market — from preapproval through closing, with the quirks specific to desert real estate.",
    whyItMatters: "First-time buyer searches are huge and competitive — but local-specific guides outperform national content. This is high-intent SEO.",
    researchData: "Standard buyer journey adapted to PS: down-payment programs (CalHFA), conventional vs FHA, dealing with HOAs and tribal lease land (see Agua Caliente checkerboard), inspection items specific to desert homes (HVAC, pool equipment, roof), property taxes via Prop 13. Mention working with a local agent saves missteps.",
  },
  {
    slug: 'palm-springs-hoa-communities',
    title: 'What Buyers Need to Know About HOA Communities in Palm Springs',
    category: 'market-update',
    city: 'Palm Springs',
    audiences: ['buyer', 'homeowner'],
    contentType: 'Market Update',
    targetKeyword: 'Palm Springs HOA communities buyer guide',
    angle: "HOA-governed properties dominate Palm Springs inventory. What buyers should understand about dues, rules, restrictions, and what their HOA actually covers before they sign.",
    whyItMatters: "HOA misunderstandings drive a huge share of post-purchase regret. Educating buyers upfront is community-service content that builds trust.",
    researchData: "Cover: monthly dues ranges ($350-$1,500+), what dues typically cover (landscaping, pool, security, sometimes water), STR restrictions (critical for vacation-home buyers), pet rules, renovation approval processes, special assessments, reserves analysis. Reference 2026 CA HOA law changes.",
  },
  {
    slug: 'best-palm-springs-vacation-home-neighborhoods',
    title: 'The Best Palm Springs Neighborhoods for Vacation Homes',
    category: 'investor-tips',
    city: 'Palm Springs',
    audiences: ['buyer', 'investor'],
    contentType: 'Investor Tips',
    targetKeyword: 'best Palm Springs neighborhoods vacation home',
    angle: "Which Palm Springs neighborhoods best balance rental demand, STR permit availability, walkability to attractions, and long-term appreciation.",
    whyItMatters: "Second-home buyers and STR investors are a huge slice of the PS market. Specific neighborhood guidance is high-value.",
    researchData: "Note Palm Springs Ordinance 2118 STR rules. Strong vacation-home neighborhoods: Movie Colony (walkable, near downtown), Old Las Palmas (luxury), Vista Las Palmas, Twin Palms, Indian Canyons (golf). Cover STR permit caps per zone.",
  },
  {
    slug: 'common-mistakes-palm-springs-homebuyers',
    title: 'Common Mistakes Palm Springs Homebuyers Make',
    category: 'market-update',
    city: 'Palm Springs',
    audiences: ['buyer'],
    contentType: 'Market Update',
    targetKeyword: 'Palm Springs homebuyer mistakes',
    angle: "The recurring missteps Shana sees buyers make — from misjudging summer ownership costs to overlooking tribal lease land — and how to avoid them.",
    whyItMatters: "Mistake-list content has high click-through rates. Specific to PS, it positions Shana as the local expert who's seen it all.",
    researchData: "Top mistakes: underestimating summer utility bills, not understanding tribal lease vs fee simple, buying STR-restricted property assuming you can rent it, skipping pool/HVAC inspection, misjudging snowbird-only neighborhoods in summer, ignoring HOA financial health.",
  },
  {
    slug: 'new-construction-vs-existing-palm-springs',
    title: 'New Construction vs. Existing Homes in Palm Springs',
    category: 'market-update',
    city: 'Palm Springs',
    audiences: ['buyer'],
    contentType: 'Market Update',
    targetKeyword: 'new construction vs existing homes Palm Springs',
    angle: "The trade-offs PS buyers face — modern energy efficiency and warranty vs mid-century architectural heritage and established neighborhoods.",
    whyItMatters: "Forces decision-stage buyers to engage with what THIS market offers (vs generic new-vs-existing tradeoffs). Strong SEO term.",
    researchData: "New construction projects: Cotino (DMV/Disney), Escena, Miralon. Existing: most PS inventory. Compare energy efficiency, HOA dynamics, lot sizes, price per sqft, resale considerations, architecture preferences. Don't pick a side — frame it as fit-to-buyer.",
  },
  {
    slug: 'seasonal-demand-palm-springs-home-sales',
    title: 'How Seasonal Demand Affects Home Sales in Palm Springs',
    category: 'market-update',
    city: 'Palm Springs',
    audiences: ['buyer', 'seller'],
    contentType: 'Market Update',
    targetKeyword: 'Palm Springs seasonal real estate market',
    angle: "The PS market has the most pronounced seasonality of any major California metro. What that means for buyers (summer deals) and sellers (winter premium).",
    whyItMatters: "Seasonal market dynamics are unique to PS. Owning this content makes Shana the go-to expert.",
    researchData: "Peak buying season Nov-March (snowbirds + festival season). Summer (May-Sep) sees fewer transactions, lower prices, slower DOM. Quantify: typical winter vs summer median price differential, typical winter vs summer transaction volume. Coachella/Stagecoach drives a brief STR-investor buying window in early spring.",
  },
  {
    slug: 'is-palm-springs-good-real-estate-investment',
    title: 'Is Palm Springs a Good Place to Invest in Real Estate?',
    category: 'investor-tips',
    city: 'Palm Springs',
    audiences: ['investor'],
    contentType: 'Investor Tips',
    targetKeyword: 'Palm Springs real estate investment',
    angle: "An honest analysis: where the PS market sits in 2026, what investors should consider, and which strategies still work.",
    whyItMatters: "Investor-focused content opens up a sophisticated buyer pool. Need to be data-driven, not hype.",
    researchData: "Cover: long-term appreciation history, cap rates for STR vs LTR, exposure to tourism cycles, climate/water risk, regulatory risk (STR ordinances), insurance cost trends. Compare to Scottsdale and Vegas. Real numbers preferred.",
  },
  {
    slug: 'palm-springs-str-regulations-guide',
    title: 'Understanding Palm Springs Short-Term Rental Regulations',
    category: 'investor-tips',
    city: 'Palm Springs',
    audiences: ['investor', 'homeowner'],
    contentType: 'Investor Tips',
    targetKeyword: 'Palm Springs short term rental rules ordinance',
    angle: "What every STR owner and prospective buyer needs to know about Palm Springs' STR ordinance, permit caps, neighbor noise rules, and enforcement.",
    whyItMatters: "STR rules change frequently. Up-to-date Palm-Springs-specific guidance is some of the highest-value content possible for the investor segment.",
    researchData: "Cover: Ordinance 2118 specifics, permit cap by zone (especially zones at 100% cap with waitlist), max nights/year per property, registration fees, TOT (transient occupancy tax) rates, noise enforcement, fines structure, recent enforcement trends. Update annually.",
  },
  {
    slug: 'vacation-rental-vs-long-term-palm-springs',
    title: 'Vacation Rental vs. Long-Term Rental: Which Is More Profitable in Palm Springs?',
    category: 'investor-tips',
    city: 'Palm Springs',
    audiences: ['investor'],
    contentType: 'Investor Tips',
    targetKeyword: 'STR vs long term rental Palm Springs profitability',
    angle: "Side-by-side P&L on the same example property: STR income vs traditional 12-month lease, after all costs.",
    whyItMatters: "Investors specifically Google this comparison. Real numbers, not generic theory, wins the click.",
    researchData: "Model a $750K, 3BR PS house: STR gross at $350-550/night × occupancy, minus cleaning, mgmt %, supplies, TOT, license, utilities. LTR gross at $3,500-4,800/month, minus mgmt, vacancy. Net annual on each. Note: STR upside, LTR stability.",
  },
  {
    slug: 'top-investment-neighborhoods-palm-springs',
    title: 'Top Neighborhoods for Investment Properties in Palm Springs',
    category: 'investor-tips',
    city: 'Palm Springs',
    audiences: ['investor'],
    contentType: 'Investor Tips',
    targetKeyword: 'best Palm Springs neighborhoods investment property',
    angle: "Which PS neighborhoods deliver the best blend of STR demand, regulatory headroom, and appreciation potential.",
    whyItMatters: "Investor-specific neighborhood guidance is uncommon and high-value.",
    researchData: "Compare: Movie Colony, Indian Canyons, Vista Las Palmas, Tahquitz River Estates. Check STR permit availability by zone. Match neighborhoods to investment thesis (cash flow vs appreciation vs lifestyle).",
  },
  {
    slug: 'how-to-analyze-palm-springs-rental-property',
    title: 'How to Analyze a Palm Springs Rental Property',
    category: 'investor-tips',
    city: 'Palm Springs',
    audiences: ['investor'],
    contentType: 'Investor Tips',
    targetKeyword: 'analyze Palm Springs rental property investment',
    angle: "A step-by-step framework — cap rate, cash-on-cash, ADR, occupancy assumptions — applied to a real PS property example.",
    whyItMatters: "Educational content for serious investors. Builds trust and authority.",
    researchData: "Walk through: pull comparable STR listings on AirDNA or local data, estimate ADR + occupancy by season, subtract operating costs, account for PS-specific items (TOT, license, pool maintenance, HOA, summer utilities). Show worked example.",
  },
  {
    slug: 'investors-buying-palm-springs',
    title: 'What Investors Should Know Before Buying in Palm Springs',
    category: 'investor-tips',
    city: 'Palm Springs',
    audiences: ['investor'],
    contentType: 'Investor Tips',
    targetKeyword: 'investor guide Palm Springs real estate',
    angle: "The investor-specific due diligence checklist most generic articles skip — STR zoning, tribal lease, HOA STR rules, insurance.",
    whyItMatters: "Sophisticated content that screens for serious buyers.",
    researchData: "Checklist: confirm STR-allowed zoning, verify permit availability (not just allowed), check HOA STR clauses, tribal lease vs fee simple, insurance availability in fire-risk areas, water rate exposure, summer utility forecasts.",
  },
  {
    slug: 'cash-flow-palm-springs-market',
    title: 'Cash Flow Opportunities in the Palm Springs Market',
    category: 'investor-tips',
    city: 'Palm Springs',
    audiences: ['investor'],
    contentType: 'Investor Tips',
    targetKeyword: 'Palm Springs cash flow rental property',
    angle: "Where positive cash flow is actually achievable in today's PS market — and where investors are betting on appreciation only.",
    whyItMatters: "Cash flow conversations are different in resort markets than primary residential markets. Useful to be specific.",
    researchData: "Cash flow under STR is achievable for $600K-$1.2M properties with good occupancy. LTR rarely cash-flows at current prices/rents — appreciation play only. Map specific price/rent combos that work.",
  },
  {
    slug: 'future-of-vacation-rentals-palm-springs',
    title: 'The Future of Vacation Rentals in Palm Springs',
    category: 'investor-tips',
    city: 'Palm Springs',
    audiences: ['investor', 'homeowner'],
    contentType: 'Investor Tips',
    targetKeyword: 'future vacation rentals Palm Springs',
    angle: "Where STR regulation, market saturation, and consumer demand are heading in PS — and what that means for current and prospective owners.",
    whyItMatters: "Forward-looking analysis is rare. Owning this lens makes Shana the analyst, not just the agent.",
    researchData: "Trend: tightening regulation across CA. PS council moves toward caps. STR oversupply in some zones. Boutique-hotel competition rising. Predict 5-yr outlook.",
  },
  {
    slug: 'tourism-impact-palm-springs-real-estate-values',
    title: 'How Tourism Impacts Palm Springs Real Estate Values',
    category: 'market-update',
    city: 'Palm Springs',
    audiences: ['investor', 'homeowner'],
    contentType: 'Market Update',
    targetKeyword: 'tourism impact Palm Springs real estate values',
    angle: "The link between PS tourism dollars and home values — and what it means when tourism slows or spikes.",
    whyItMatters: "Connects macro narrative (tourism) to micro outcome (your home value). Strong educational piece.",
    researchData: "Cover: Coachella + Stagecoach combined economic impact ($700M+), Modernism Week, film festival, year-round tourism. Tie to home values: higher visitor count → STR demand → buyer demand → prices. Cover risk if tourism declines.",
  },
  {
    slug: 'investment-mistakes-resort-markets',
    title: 'Common Investment Mistakes in Resort Markets',
    category: 'investor-tips',
    city: 'Palm Springs',
    audiences: ['investor'],
    contentType: 'Investor Tips',
    targetKeyword: 'resort market investment mistakes',
    angle: "Why buying in PS isn't the same as buying in a primary residential market — and the resort-market-specific pitfalls investors stumble into.",
    whyItMatters: "Frames PS as a resort market with unique dynamics. Educational, builds expertise positioning.",
    researchData: "Mistakes: assuming summer demand mirrors winter, underestimating seasonal carrying costs, buying STR-prohibited property without checking, ignoring climate/water risk premiums on insurance, overpaying during peak season frenzy.",
  },
]

// ── Luxury & second-home content ─────────────────────────────────────────
const LUXURY_CONTENT: EvergreenSeed[] = [
  {
    slug: 'why-luxury-buyers-love-palm-springs',
    title: 'Why Luxury Buyers Love Palm Springs',
    category: 'community',
    city: 'Palm Springs',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'luxury buyers Palm Springs real estate',
    angle: "The mix of factors — architecture, privacy, climate, cultural cachet, proximity to LA — that keeps Palm Springs at the top of the luxury second-home list.",
    whyItMatters: "Luxury-buyer-targeted content captures a high-value segment and signals Shana operates at that price point.",
    researchData: "Architecture density (Neutra, Frey, Lautner), privacy culture, 90-min from LA, dry climate easier on health, Sunnylands prestige halo, top private clubs (BIGHORN, Madison, Vintage), Modernism Week.",
  },
  {
    slug: 'rise-second-home-ownership-palm-springs',
    title: 'The Rise of Second-Home Ownership in Palm Springs',
    category: 'market-update',
    city: 'Palm Springs',
    audiences: ['buyer', 'investor'],
    contentType: 'Market Update',
    targetKeyword: 'second home Palm Springs trends',
    angle: "Why PS is one of the fastest-growing second-home markets in the country — and what that means for inventory, prices, and lifestyle for everyone here.",
    whyItMatters: "Macro trend story that contextualizes Shana's business and helps potential clients understand what's driving the market.",
    researchData: "Remote-work permanence post-2020. CA migration to lower-cost in-state options. PS proximity to LA primary markets. Quantify share of CV transactions that are second-home purchases.",
  },
  {
    slug: 'features-define-luxury-palm-springs-homes',
    title: 'Features That Define Luxury Homes in Palm Springs',
    category: 'community',
    city: 'Palm Springs',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'luxury home features Palm Springs',
    angle: "Beyond square footage — the specific design and amenity features that define what 'luxury' actually means in the PS market.",
    whyItMatters: "Educates aspirational buyers and frames Shana's expertise in the segment.",
    researchData: "Mountain views (San Jacinto), pool + spa + entertaining outdoor kitchen, mid-century pedigree, named architect, walls of glass, indoor-outdoor flow, smart home automation, private gated entry, golf-course frontage.",
  },
  {
    slug: 'mid-century-modern-palm-springs-signature',
    title: "Mid-Century Modern Homes: Palm Springs' Signature Style",
    category: 'local-history',
    city: 'Palm Springs',
    audiences: ['buyer', 'local'],
    contentType: 'Local History',
    targetKeyword: 'mid century modern homes Palm Springs',
    angle: "What makes a home 'mid-century modern,' which architects to know, and how to spot the real deal vs the homages.",
    whyItMatters: "MCM is the defining PS architectural identity. Mastering this content is table-stakes for any PS agent.",
    researchData: "Era: 1945-1975. Key architects: Albert Frey, Richard Neutra, William Krisel, Donald Wexler, Donald Hicks, E. Stewart Williams. Hallmarks: post-and-beam, walls of glass, butterfly/folded-plate roofs, breeze blocks, integration with landscape. Key tract: Alexander homes.",
  },
  {
    slug: 'how-to-buy-seasonal-home-palm-springs',
    title: 'How to Buy a Seasonal Home in Palm Springs',
    category: 'investor-tips',
    city: 'Palm Springs',
    audiences: ['buyer', 'investor'],
    contentType: 'Investor Tips',
    targetKeyword: 'buying seasonal home Palm Springs guide',
    angle: "The practical mechanics of buying a part-time residence in PS — financing, property management, summer dormancy planning, HOA considerations.",
    whyItMatters: "Specific to second-home buyers — a major slice of the PS market — and exactly the kind of guide they search for.",
    researchData: "Cover: second-home vs investment property financing (different rates, different DSCR), property management options, summer shutdown protocols (HVAC monitoring, pool maintenance, monsoon prep), HOA snowbird rules, tax implications.",
  },
  {
    slug: 'luxury-trends-palm-springs-market',
    title: 'Luxury Home Trends Shaping the Palm Springs Market',
    category: 'market-update',
    city: 'Palm Springs',
    audiences: ['buyer'],
    contentType: 'Market Update',
    targetKeyword: 'luxury Palm Springs market trends',
    angle: "What luxury buyers are demanding in 2026 — and how the PS market is responding.",
    whyItMatters: "Topical, signals current-market expertise.",
    researchData: "Trends: passive design (high heat resistance), restored vs. updated MCM debate, primary suites with wellness rooms, EV infrastructure, outdoor cooling tech (misters, shade structures), smaller luxury homes vs traditional estates.",
  },
  {
    slug: 'most-exclusive-communities-palm-springs',
    title: 'The Most Exclusive Communities in Palm Springs',
    category: 'community',
    city: 'Palm Springs',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'exclusive gated communities Palm Springs',
    angle: "The private clubs, gated communities, and ultra-prime addresses that anchor Palm Springs' luxury segment.",
    whyItMatters: "Concentrated luxury-buyer SEO.",
    researchData: "Cover: The Madison Club (La Quinta), BIGHORN Golf Club (PD), Vintage Club (Indian Wells), Andreas Hills, Old Las Palmas, Hideaway. Note exclusivity, initiation fees, signature features.",
  },
  {
    slug: 'high-net-worth-buyers-desert-properties',
    title: 'What High-Net-Worth Buyers Look for in Desert Properties',
    category: 'community',
    city: 'Palm Springs',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'high net worth desert real estate buyer',
    angle: "From the agent's perspective — what HNW buyers specifically prioritize in a desert second home that primary-market buyers might not.",
    whyItMatters: "Positions Shana as someone who works in the luxury segment.",
    researchData: "Priorities: privacy & security, architectural pedigree (named architect = collector cache), entertaining capacity, outdoor space, low-maintenance landscape, proximity to private aviation (PSP), staff accommodations.",
  },
]

// ── Palm Springs history & architecture deep-dives ───────────────────────
const HISTORY_DEEPDIVES: EvergreenSeed[] = [
  {
    slug: 'history-palm-springs-real-estate',
    title: 'The History of Palm Springs Real Estate',
    category: 'local-history',
    city: 'Palm Springs',
    audiences: ['local', 'buyer'],
    contentType: 'Local History',
    targetKeyword: 'history of Palm Springs real estate',
    angle: "From Cahuilla settlement to Hollywood retreat to international design capital — the 150-year arc of PS real estate.",
    whyItMatters: "Foundational evergreen. Establishes Shana as a local historian, not just an agent.",
    researchData: "Cahuilla pre-1876. 1876 reservation/checkerboard. 1920s discovery. 1947 architecture boom. 2000s preservation movement. 2020s remote-work driven boom.",
  },
  {
    slug: 'palm-springs-resort-destination-origin',
    title: 'How Palm Springs Became a Resort Destination',
    category: 'local-history',
    city: 'Palm Springs',
    audiences: ['local', 'buyer'],
    contentType: 'Local History',
    targetKeyword: 'Palm Springs resort destination history',
    angle: "How a dusty stagecoach stop became one of America's premier resort destinations — the people, hotels, and decisions that made it.",
    whyItMatters: "Connects past to present market identity.",
    researchData: "El Mirador Hotel (1928), Racquet Club (1934), 'two-hour rule' for studio contracts, 1950s Rat Pack era, the late-90s/2000s reinvention via design tourism (Modernism Week).",
  },
  {
    slug: 'rise-mid-century-modern-architecture',
    title: 'The Rise of Mid-Century Modern Architecture in Palm Springs',
    category: 'local-history',
    city: 'Palm Springs',
    audiences: ['local', 'buyer'],
    contentType: 'Local History',
    targetKeyword: 'mid century modern architecture Palm Springs history',
    angle: "Why so many of America's greatest 20th-century architects built in this one small desert city — and what made the 1947-1965 era unrepeatable.",
    whyItMatters: "The defining PS story. Owning this content is essential.",
    researchData: "Climate forced experimentation, Hollywood money funded experimentation, small close-knit architect community, Alexander Construction Company industrialized the style, decline 1970s, revival 1990s-present.",
  },
  {
    slug: 'famous-architects-palm-springs',
    title: 'Famous Architects Who Shaped Palm Springs',
    category: 'local-history',
    city: 'Palm Springs',
    audiences: ['buyer', 'local'],
    contentType: 'Local History',
    targetKeyword: 'famous architects Palm Springs mid century',
    angle: "A guide to the architects whose work defines Palm Springs — and the homes they built that are still here.",
    whyItMatters: "MCM buyers specifically seek out named-architect homes. Educational content.",
    researchData: "Albert Frey (PS City Hall, Tramway Valley Station, Frey House II). Richard Neutra (Kaufmann House). William Krisel (Alexander tracts). Donald Wexler (steel houses). E. Stewart Williams (Sinatra's Twin Palms, Coachella Valley Savings & Loan). John Lautner (Bob Hope Estate). Donald Hicks. A. Quincy Jones (Sunnylands).",
  },
  {
    slug: 'historic-neighborhoods-palm-springs-buyers',
    title: 'Historic Neighborhoods Every Palm Springs Buyer Should Know',
    category: 'local-history',
    city: 'Palm Springs',
    audiences: ['buyer'],
    contentType: 'Local History',
    targetKeyword: 'historic Palm Springs neighborhoods',
    angle: "The handful of PS neighborhoods with the deepest historical significance — and what buying into them actually means.",
    whyItMatters: "Specific-neighborhood SEO with historical depth.",
    researchData: "Movie Colony (Sinatra, Crosby, Liberace), Old Las Palmas, Vista Las Palmas, Twin Palms (the tract, not Sinatra's house), Tahquitz River Estates, Deepwell, Indian Canyons.",
  },
  {
    slug: 'celebrity-homes-impact-palm-springs',
    title: 'Celebrity Homes and Their Impact on Palm Springs',
    category: 'local-history',
    city: 'Palm Springs',
    audiences: ['local', 'buyer'],
    contentType: 'Local History',
    targetKeyword: 'celebrity homes Palm Springs',
    angle: "How the concentration of celebrity ownership built (and still builds) PS real estate values — beyond the obvious novelty factor.",
    whyItMatters: "Pop-cultural angle on real estate economics — broad appeal.",
    researchData: "Specific celebrity homes that have changed hands publicly, the 'celebrity halo' effect on neighborhood prices, the role of public auctions/listings as market events.",
  },
  {
    slug: 'how-hollywood-built-palm-springs',
    title: 'How Hollywood Helped Build Palm Springs',
    category: 'local-history',
    city: 'Palm Springs',
    audiences: ['local', 'buyer'],
    contentType: 'Local History',
    targetKeyword: 'Hollywood Palm Springs history',
    angle: "The studio era's two-hour rule, Frank Sinatra's pull, and the chain reaction that turned a desert outpost into a Hollywood enclave.",
    whyItMatters: "Origin-story content with broad appeal.",
    researchData: "1920s-1960s. Studio contracts requiring stars to be available within 2hrs of LA. Sinatra's Twin Palms (1947) as social capital. Influence on architectural commissions.",
  },
  {
    slug: 'architectural-styles-palm-springs',
    title: 'Architectural Styles Found Throughout Palm Springs',
    category: 'community',
    city: 'Palm Springs',
    audiences: ['buyer', 'local'],
    contentType: 'Community',
    targetKeyword: 'Palm Springs architectural styles guide',
    angle: "Beyond MCM — the Spanish Colonial, Modern Desert, Pueblo Revival, and contemporary styles that fill out PS' built environment.",
    whyItMatters: "Educational content showing PS is more than MCM.",
    researchData: "Spanish Colonial Revival (1920s-30s), Mid-Century Modern (1945-75), Modern Desert / Desert Contemporary (2000s+), Pueblo Revival, Hacienda. Match styles to neighborhoods.",
  },
  {
    slug: 'preserving-historic-homes-palm-springs',
    title: 'Preserving Historic Homes in Palm Springs',
    category: 'local-history',
    city: 'Palm Springs',
    audiences: ['homeowner', 'buyer'],
    contentType: 'Local History',
    targetKeyword: 'preserving historic homes Palm Springs',
    angle: "What it actually takes to own and preserve a historically significant PS home — designations, restrictions, tax benefits, and the community of stewards.",
    whyItMatters: "Specialty content for the architecture-loving buyer segment.",
    researchData: "Class 1 Historic Site Designation, Class 2 (contributing), Mills Act tax benefits, PS Preservation Foundation, restoration vs renovation debate, finding period-appropriate contractors.",
  },
]

// ── Coachella Valley cross-city & relocation ─────────────────────────────
const COACHELLA_VALLEY_GUIDES: EvergreenSeed[] = [
  {
    slug: 'moving-to-coachella-valley-guide',
    title: 'Moving to Coachella Valley: Everything You Need to Know',
    category: 'community',
    city: 'Coachella Valley',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'moving to Coachella Valley California guide',
    angle: "The relocation playbook — choosing a city, planning the move, registering everything, settling in. Written from a local's POV.",
    whyItMatters: "Massive evergreen SEO target. Captures relocators researching the area broadly.",
    researchData: "City selection criteria, choosing a school district (without making rating claims), DMV / utility / voter registration logistics, finding a doctor, the snowbird arrival pattern, getting through summer for the first time.",
  },
  {
    slug: 'which-coachella-valley-city-fits-you',
    title: 'Which Coachella Valley City Is Right for You?',
    category: 'community',
    city: 'Coachella Valley',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'which Coachella Valley city best fit',
    angle: "Palm Springs vs Palm Desert vs Rancho Mirage vs La Quinta vs Indian Wells — matching buyer profile to the right CV city.",
    whyItMatters: "Decision-making content for buyers narrowing their search.",
    researchData: "Match buyer types: nightlife/walkable (PS), shopping/dining (PD/El Paseo), luxury/quiet (RM/IW), golf/family (LQ), affordable/up-and-coming (Indio/CC/DHS/Coachella).",
  },
  {
    slug: 'best-remote-worker-communities-cv',
    title: 'Best Communities for Remote Workers in Coachella Valley',
    category: 'community',
    city: 'Coachella Valley',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'best Coachella Valley communities remote work',
    angle: "Where remote workers are landing in CV and why — fiber availability, coworking, lifestyle balance, year-round livability.",
    whyItMatters: "Captures the remote-work relocator market — a major buyer segment post-2020.",
    researchData: "Fiber/gigabit availability by city, coworking spaces (Whitewater Co, etc.), best 'home office with view' neighborhoods, year-round vs snowbird-heavy zones.",
  },
  {
    slug: 'californians-relocating-coachella-valley',
    title: 'Where Are Californians Relocating Within the Coachella Valley?',
    category: 'market-update',
    city: 'Coachella Valley',
    audiences: ['buyer'],
    contentType: 'Market Update',
    targetKeyword: 'Californians relocating Coachella Valley',
    angle: "Migration data — which CV cities are gaining residents from LA, SF, SD — and why.",
    whyItMatters: "Data-driven story about market direction. Strong shareability.",
    researchData: "Pull CA migration data + CV permit/sales data. Highlight which feeder metros (LA, SD, SF) drive which CV city. Tie to lifestyle/cost-of-living drivers.",
  },
  {
    slug: 'most-affordable-cities-coachella-valley',
    title: 'Most Affordable Cities in Coachella Valley for Homebuyers',
    category: 'market-update',
    city: 'Coachella Valley',
    audiences: ['buyer'],
    contentType: 'Market Update',
    targetKeyword: 'affordable Coachella Valley cities homebuyers',
    angle: "Where first-time and value-conscious buyers can still find entry-level homes — and what to expect at those price points.",
    whyItMatters: "Affordability is a top-five real estate search term globally. CV-specific = strong SEO.",
    researchData: "Desert Hot Springs, Indio, Coachella, Cathedral City sub-markets. Median home prices, types of inventory, neighborhood quality, commute considerations.",
  },
  {
    slug: 'best-retiree-cities-coachella-valley',
    title: 'Best Places for Retirees in Coachella Valley',
    category: 'community',
    city: 'Coachella Valley',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'best retiree cities Coachella Valley',
    angle: "What retirees should look for in a CV city — climate, healthcare proximity, walkability, community, cost — and which cities deliver.",
    whyItMatters: "Retirees are a primary CV buyer demographic.",
    researchData: "Healthcare proximity (Eisenhower Medical Center, Desert Regional), 55+ communities (Sun City Palm Desert, Trilogy, Del Webb), low-maintenance HOA properties, climate considerations for elderly residents.",
  },
]

// ── Rancho Mirage deep-dive ──────────────────────────────────────────────
const RANCHO_MIRAGE: EvergreenSeed[] = [
  {
    slug: 'rancho-mirage-playground-of-presidents',
    title: 'Why Rancho Mirage Is Known as the Playground of Presidents',
    category: 'local-history',
    city: 'Rancho Mirage',
    audiences: ['buyer', 'local'],
    contentType: 'Local History',
    targetKeyword: 'Rancho Mirage playground presidents history',
    angle: "Sunnylands, Camp David West, Eisenhower-to-Obama — the history that earned Rancho Mirage its political prestige.",
    whyItMatters: "Specific origin story for a city that commands a real estate premium tied to history.",
    researchData: "Sunnylands (Annenberg) hosted every president Eisenhower-Obama. Ford lived locally. Reagan's New Year's tradition. Eisenhower wing of Eisenhower Medical Center. Bob Hope Drive, Frank Sinatra Drive.",
  },
  {
    slug: 'mission-hills-country-club-real-estate-guide',
    title: 'Mission Hills Country Club Real Estate Guide',
    category: 'community',
    city: 'Rancho Mirage',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'Mission Hills Country Club Rancho Mirage real estate',
    angle: "Inside the Rancho Mirage golf-and-tennis community where Dinah Shore hosted the LPGA major — homes, fees, lifestyle, market trends.",
    whyItMatters: "Community-specific deep-dives consistently outperform broad neighborhood content for SEO and lead quality.",
    researchData: "Mission Hills CC: three golf courses (Pete Dye Challenge, Arnold Palmer, Gary Player), former host of Dinah Shore Classic. HOA dues, club initiation, property mix (condos to estates), price ranges.",
  },
  {
    slug: 'best-luxury-communities-rancho-mirage',
    title: 'Best Luxury Communities in Rancho Mirage',
    category: 'community',
    city: 'Rancho Mirage',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'best luxury communities Rancho Mirage',
    angle: "The gated and private-club communities that define luxury living in Rancho Mirage.",
    whyItMatters: "High-intent luxury buyer search.",
    researchData: "The Vintage Club, Tamarisk CC, Mission Hills CC, Thunderbird Heights, Morningside, Springs CC. Initiation fees, dues, signature amenities, price ranges.",
  },
  {
    slug: 'rancho-mirage-market-trends',
    title: 'Rancho Mirage Market Trends Explained',
    category: 'market-update',
    city: 'Rancho Mirage',
    audiences: ['buyer', 'seller', 'homeowner'],
    contentType: 'Market Update',
    targetKeyword: 'Rancho Mirage real estate market trends',
    angle: "Current state of the Rancho Mirage market — inventory, days on market, buyer profiles, what's selling.",
    whyItMatters: "City-specific market content is high-value local SEO.",
    researchData: "Pull current MLS data. Note RM tends toward higher-end inventory, longer DOM than PS, snowbird-heavy.",
  },
  {
    slug: 'rancho-mirage-attracts-luxury-buyers',
    title: 'How Rancho Mirage Attracts Luxury Buyers',
    category: 'community',
    city: 'Rancho Mirage',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'why luxury buyers Rancho Mirage',
    angle: "Privacy, prestige, established luxury infrastructure — the through-line that makes RM the choice for buyers a notch quieter than PS.",
    whyItMatters: "Positioning content for the luxury segment.",
    researchData: "Sunnylands halo, private clubs, hospital proximity (Eisenhower), quiet street grid, mature landscaping, no Coachella festival proximity issues.",
  },
  {
    slug: 'new-residential-developments-rancho-mirage',
    title: 'New Residential Developments in Rancho Mirage',
    category: 'trending-topics',
    city: 'Rancho Mirage',
    audiences: ['buyer', 'investor'],
    contentType: 'Trending',
    targetKeyword: 'new developments Rancho Mirage 2026',
    angle: "What's being built in RM right now — and what each project signals about the market direction.",
    whyItMatters: "Captures buyers looking for new-construction inventory and surfaces market-direction stories.",
    researchData: "Pull current planning department filings. Notable: Del Webb Rancho Mirage expansion, custom estate lots in luxury zones, retail/mixed-use projects.",
  },
  {
    slug: 'best-gated-communities-rancho-mirage',
    title: 'Best Gated Communities in Rancho Mirage',
    category: 'community',
    city: 'Rancho Mirage',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'best gated communities Rancho Mirage',
    angle: "From private golf clubs to gated 55+ neighborhoods — the full spectrum of gated living in Rancho Mirage.",
    whyItMatters: "Gated-community buyers know they want a gate; helping them choose which is direct lead generation.",
    researchData: "The Vintage Club, Mission Hills CC, Thunderbird Heights, Morningside, Springs CC, Del Webb Rancho Mirage, Mission Hills East, Sunrise CC. Compare lifestyle, fees, security, demographics.",
  },
]

// ── Indian Wells deep-dive ───────────────────────────────────────────────
const INDIAN_WELLS: EvergreenSeed[] = [
  {
    slug: 'indian-wells-most-exclusive-cv-city',
    title: "Why Indian Wells Is One of the Valley's Most Exclusive Cities",
    category: 'community',
    city: 'Indian Wells',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'Indian Wells exclusive city Coachella Valley',
    angle: "Small footprint, big amenities, top-tier home values — what makes Indian Wells the CV's quietest powerhouse.",
    whyItMatters: "Indian Wells punches above its weight in luxury real estate. Few articles capture why specifically.",
    researchData: "Smallest pop of CV cities (5K+), highest median home price, Indian Wells Tennis Garden (BNP Paribas Open), top-rated resort hotels, exclusive private clubs.",
  },
  {
    slug: 'indian-wells-country-club-real-estate',
    title: 'Indian Wells Country Club Real Estate Overview',
    category: 'community',
    city: 'Indian Wells',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'Indian Wells Country Club real estate',
    angle: "Inside Indian Wells Country Club — homes, golf, dues, community.",
    whyItMatters: "Community-specific deep-dives are high-converting.",
    researchData: "IWCC: 18-hole golf course, tennis, social. Price range, dues, lifestyle profile.",
  },
  {
    slug: 'luxury-living-indian-wells',
    title: 'Luxury Living in Indian Wells',
    category: 'community',
    city: 'Indian Wells',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'luxury Indian Wells living lifestyle',
    angle: "The day-in-the-life of luxury living in Indian Wells — clubs, tennis, golf, hotels, dining.",
    whyItMatters: "Lifestyle content for the city's primary buyer.",
    researchData: "Tennis Garden, Toscana CC, Vintage Club proximity, top hotels (Hyatt Regency, Miramonte), El Paseo nearby. Mention BNP Paribas Open impact.",
  },
  {
    slug: 'what-makes-indian-wells-unique',
    title: 'What Makes Indian Wells Unique?',
    category: 'community',
    city: 'Indian Wells',
    audiences: ['buyer', 'local'],
    contentType: 'Community',
    targetKeyword: 'what makes Indian Wells unique',
    angle: "Walking through what sets Indian Wells apart from neighboring cities — and why those quirks attract the buyers it does.",
    whyItMatters: "Decision-stage buyer content.",
    researchData: "Tiny population, no commercial sprawl, low retail tax (resident benefits), tennis identity, snowbird-heavy, more horizontal than vertical density.",
  },
  {
    slug: 'new-luxury-developments-indian-wells',
    title: 'New Luxury Developments in Indian Wells',
    category: 'trending-topics',
    city: 'Indian Wells',
    audiences: ['buyer', 'investor'],
    contentType: 'Trending',
    targetKeyword: 'new luxury developments Indian Wells',
    angle: "What's being built (or recently completed) in Indian Wells at the luxury end of the market.",
    whyItMatters: "Captures luxury new-build inquiries.",
    researchData: "Toscana CC expansion, custom estates, any new private club construction. Pull current planning filings.",
  },
  {
    slug: 'indian-wells-home-values-explained',
    title: 'Indian Wells Home Values Explained',
    category: 'market-update',
    city: 'Indian Wells',
    audiences: ['buyer', 'seller', 'homeowner'],
    contentType: 'Market Update',
    targetKeyword: 'Indian Wells home values 2026',
    angle: "Why Indian Wells home values stay high — supply constraints, demographic stability, club premium, low-density zoning.",
    whyItMatters: "Owner/seller-facing content showing market understanding.",
    researchData: "Median home price, price/sqft trends, inventory levels, DOM, share of homes in private clubs.",
  },
  {
    slug: 'buying-second-home-indian-wells',
    title: 'Buying a Second Home in Indian Wells',
    category: 'investor-tips',
    city: 'Indian Wells',
    audiences: ['buyer', 'investor'],
    contentType: 'Investor Tips',
    targetKeyword: 'second home Indian Wells buyer guide',
    angle: "What second-home buyers should know about Indian Wells specifically — clubs, snowbird patterns, summer management.",
    whyItMatters: "IW is primarily second-home territory. Targeted guide.",
    researchData: "Most IW homes are second residences. Cover summer dormancy, club membership benefits when away, snowbird arrival/departure patterns, property mgmt locally.",
  },
]

// ── Development & infrastructure ─────────────────────────────────────────
const DEVELOPMENT_PROJECTS: EvergreenSeed[] = [
  {
    slug: 'major-cv-development-projects-watch',
    title: 'Major Coachella Valley Development Projects to Watch',
    category: 'trending-topics',
    city: 'Coachella Valley',
    audiences: ['buyer', 'investor', 'local'],
    contentType: 'Trending',
    targetKeyword: 'Coachella Valley development projects 2026',
    angle: "The five or six big projects breaking ground or in entitlement that will shape CV property values over the next decade.",
    whyItMatters: "Forward-looking content. Big developments = long-term value signals. Exactly the kind of post the client called out specifically.",
    researchData: "Track: Cotino (DMV/Disney) Rancho Mirage, downtown PS revitalization, La Quinta Village expansion, Indio convention/event projects, hospital expansions, university/college campus moves. Frame: investment confidence.",
  },
  {
    slug: 'upcoming-mixed-use-developments-cv',
    title: 'Upcoming Mixed-Use Developments in Coachella Valley',
    category: 'trending-topics',
    city: 'Coachella Valley',
    audiences: ['buyer', 'investor'],
    contentType: 'Trending',
    targetKeyword: 'mixed use developments Coachella Valley',
    angle: "The mixed-use projects (retail + residential + hospitality) that signal CV's evolution from purely residential markets toward walkable urban-style districts.",
    whyItMatters: "Mixed-use is the dominant new-development pattern and a strong long-term value signal.",
    researchData: "Pull active project filings from Palm Desert (multiple), Palm Springs downtown, Indio. Note size, anchor uses, completion timeline.",
  },
  {
    slug: 'future-downtown-palm-springs',
    title: 'The Future of Downtown Palm Springs',
    category: 'trending-topics',
    city: 'Palm Springs',
    audiences: ['buyer', 'investor', 'local'],
    contentType: 'Trending',
    targetKeyword: 'future downtown Palm Springs',
    angle: "Where downtown PS is heading — new hotels, residential infill, the lingering effects of the Plaza redevelopment, the post-COVID tourism shape.",
    whyItMatters: "Downtown direction affects nearby property values directly.",
    researchData: "Recent + planned: hotel projects, Spa Resort Casino, PS Convention Center redevelopment, Plaza Theatre revival, condo conversions, restaurant scene maturation.",
  },
  {
    slug: 'tourism-drives-local-real-estate-demand',
    title: 'How Tourism Drives Local Real Estate Demand',
    category: 'market-update',
    city: 'Coachella Valley',
    audiences: ['buyer', 'investor', 'homeowner'],
    contentType: 'Market Update',
    targetKeyword: 'tourism real estate demand Coachella Valley',
    angle: "The mechanism — visitor → STR booking → STR investor → seasonal resident → permanent buyer — and where in the CV that funnel works best.",
    whyItMatters: "Macro narrative that affects every CV property owner.",
    researchData: "$700M+ Coachella/Stagecoach impact, 16M annual visitors to PS, hotel occupancy trends, downstream effect on STR demand and home values.",
  },
  {
    slug: 'economic-growth-trends-cv',
    title: 'Economic Growth Trends Across Coachella Valley',
    category: 'market-update',
    city: 'Coachella Valley',
    audiences: ['buyer', 'investor'],
    contentType: 'Market Update',
    targetKeyword: 'Coachella Valley economic growth trends',
    angle: "Where CV's economy is diversifying beyond tourism and ag — clean energy, biotech, healthcare, education.",
    whyItMatters: "Counters the 'tourism-only' perception; signals economic resilience.",
    researchData: "Clean energy projects (solar farms), biotech investments, healthcare expansion (Eisenhower, Desert Regional), Coachella Valley colleges/universities, ag-tech.",
  },
  {
    slug: 'new-retail-entertainment-developments',
    title: 'New Retail and Entertainment Developments in Coachella Valley',
    category: 'trending-topics',
    city: 'Coachella Valley',
    audiences: ['local', 'buyer'],
    contentType: 'Trending',
    targetKeyword: 'new retail entertainment Coachella Valley',
    angle: "The retail and entertainment additions landing in CV — restaurants, theaters, music venues, retail.",
    whyItMatters: "Quality-of-life content with lifestyle pull. Tied to property values.",
    researchData: "Pull recent openings: restaurants, bars, music venues (Acrisure Arena), new retail in PD/IW, golf simulator/pickleball venues, art galleries.",
  },
  {
    slug: 'what-new-residents-cv-growth',
    title: 'What New Residents Should Know About Valley Growth',
    category: 'community',
    city: 'Coachella Valley',
    audiences: ['buyer', 'local'],
    contentType: 'Community',
    targetKeyword: 'Coachella Valley growth new residents',
    angle: "Honest picture of where CV is growing fast, where it isn't, and what it means for incoming residents.",
    whyItMatters: "Welcoming + informative content for relocators.",
    researchData: "Population trends by city, traffic patterns, water/infrastructure stress, where amenities are improving vs lagging.",
  },
]

// ── Lifestyle & activities ──────────────────────────────────────────────
const LIFESTYLE: EvergreenSeed[] = [
  {
    slug: 'living-near-el-paseo',
    title: 'Living Near El Paseo: The Rodeo Drive of the Desert',
    category: 'community',
    city: 'Palm Desert',
    audiences: ['buyer', 'local'],
    contentType: 'Community',
    targetKeyword: 'living near El Paseo Palm Desert',
    angle: "What it's like to live a short walk from CV's premier shopping street — the neighborhoods, the home types, the trade-offs.",
    whyItMatters: "Highly searchable specific-location content.",
    researchData: "Neighborhoods within walking distance of El Paseo: Marrakesh CC, Vista Paseo, Hovley Lane communities. Mix of condos and single-family. Note pedestrian access, holiday foot traffic, peak-season parking, art gallery walks (1st Thursday).",
  },
  {
    slug: 'best-hiking-communities-cv',
    title: 'Best Hiking Communities in Coachella Valley',
    category: 'community',
    city: 'Coachella Valley',
    audiences: ['buyer', 'local'],
    contentType: 'Community',
    targetKeyword: 'best hiking neighborhoods Coachella Valley',
    angle: "If trail access matters to you, here's where to look — the neighborhoods backing onto Indian Canyons, Bump and Grind, Lykken, La Quinta Cove.",
    whyItMatters: "Lifestyle-driven SEO, captures active buyers.",
    researchData: "Indian Canyons trailheads (PS, Andreas Hills), Bump and Grind (PD), Lykken Trail (PS Mesa), La Quinta Cove (LQ), Boo Hoff Trail. Match neighborhoods to trail access.",
  },
  {
    slug: 'appeal-resort-style-living',
    title: 'The Appeal of Resort-Style Living',
    category: 'community',
    city: 'Coachella Valley',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'resort style living Coachella Valley',
    angle: "What 'resort-style living' actually means in CV — pools, clubs, services, vacation-from-home reality.",
    whyItMatters: "Lifestyle aspirational content. Broad appeal.",
    researchData: "Resort-style communities: Trilogy at La Quinta, Sun City Palm Desert, Trilogy Polo Club, Mission Hills. Pools, fitness, social calendar, dining on-property.",
  },
  {
    slug: 'best-snowbird-neighborhoods-cv',
    title: 'Best Neighborhoods for Snowbirds in Coachella Valley',
    category: 'community',
    city: 'Coachella Valley',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'best snowbird neighborhoods Coachella Valley',
    angle: "Where snowbirds settle — and why some neighborhoods feel like ghost towns in summer while others stay active year-round.",
    whyItMatters: "Captures the snowbird buyer segment — huge in CV.",
    researchData: "Heavy snowbird zones: Sun City PD, Indian Wells, Mission Hills, Trilogy. Year-round zones: most of PS, Cathedral City. Note summer occupancy %, snowbird-only services, HOA snowbird programs.",
  },
  {
    slug: 'outdoor-living-desert-real-estate',
    title: 'Why Outdoor Living Matters in Desert Real Estate',
    category: 'community',
    city: 'Coachella Valley',
    audiences: ['buyer'],
    contentType: 'Community',
    targetKeyword: 'outdoor living desert homes Coachella Valley',
    angle: "Pool, patio, outdoor kitchen, shade structures, misters — why outdoor space drives value in CV more than almost any other market.",
    whyItMatters: "Educates buyers on what matters; positions Shana as a desert specialist.",
    researchData: "Pool + spa nearly required for value, outdoor kitchens, shade tech (cantilevered awnings, retractable), mister systems, fire pits for winter evenings. ROI on outdoor improvements.",
  },
  {
    slug: 'top-dining-destinations-cv-communities',
    title: 'Top Dining Destinations Near Popular Communities',
    category: 'community',
    city: 'Coachella Valley',
    audiences: ['local', 'buyer'],
    contentType: 'Community',
    targetKeyword: 'best restaurants Coachella Valley',
    angle: "Best restaurants by neighborhood — what you'd walk to if you lived there.",
    whyItMatters: "Lifestyle/food content has high engagement and shareability.",
    researchData: "PS downtown (Lulu, Workshop, Eight4Nine), El Paseo (Eureka, Daily Grill), La Quinta Old Town, Indian Wells resort dining, Cathedral City growing scene.",
  },
  {
    slug: 'weekend-activities-cv-residents',
    title: 'Weekend Activities for Coachella Valley Residents',
    category: 'community',
    city: 'Coachella Valley',
    audiences: ['local'],
    contentType: 'Community',
    targetKeyword: 'weekend activities Coachella Valley',
    angle: "Beyond hiking and golf — what locals actually do on weekends, seasonally.",
    whyItMatters: "Local-engagement content. Builds the community connection that drives word-of-mouth.",
    researchData: "Farmers markets (Sundays in PS, Saturdays in PD), street fairs, gallery walks, Saturday tennis at Tennis Garden, scenic drives (Joshua Tree, Salton Sea), Aerial Tramway, Indian Canyons.",
  },
]

// ── Market data & analysis ──────────────────────────────────────────────
const MARKET_ANALYSIS: EvergreenSeed[] = [
  {
    slug: 'monthly-cv-market-update-template',
    title: 'Coachella Valley Real Estate Market Update',
    category: 'market-update',
    city: 'Coachella Valley',
    audiences: ['buyer', 'seller', 'homeowner'],
    contentType: 'Market Update',
    targetKeyword: 'Coachella Valley real estate market update',
    angle: "Monthly market vital signs: median price, inventory, days on market, what's selling fastest. Updated monthly.",
    whyItMatters: "Recurring monthly content that builds search authority for market terms.",
    researchData: "Pull current MLS data from Coachella Valley MLS / search.searchcoachellavalleyhomes.com. Compare to same month prior year + prior month. Highlight outliers.",
  },
  {
    slug: 'year-over-year-cv-price-trends',
    title: 'Year-over-Year Home Price Trends by Coachella Valley City',
    category: 'market-update',
    city: 'Coachella Valley',
    audiences: ['buyer', 'seller', 'homeowner'],
    contentType: 'Market Update',
    targetKeyword: 'year over year home prices Coachella Valley',
    angle: "City-by-city YoY price changes — who's heating up, who's cooling, who's holding steady.",
    whyItMatters: "Data-driven content with high evergreen value.",
    researchData: "Pull median price YoY by city: PS, PD, RM, IW, LQ, Indio, CC, DHS, Coachella. Note % change and absolute. Highlight any cities going against trend.",
  },
  {
    slug: 'fastest-growing-cv-neighborhoods',
    title: 'Fastest-Growing Neighborhoods in Coachella Valley',
    category: 'market-update',
    city: 'Coachella Valley',
    audiences: ['buyer', 'investor'],
    contentType: 'Market Update',
    targetKeyword: 'fastest growing Coachella Valley neighborhoods',
    angle: "By appreciation, by population, by new construction — the CV neighborhoods seeing the most movement.",
    whyItMatters: "Forward-looking buyer/investor content.",
    researchData: "Use MLS appreciation data + census + permit filings. Likely contenders: emerging Indio neighborhoods, Cathedral City pockets, Coachella growth zones.",
  },
  {
    slug: 'best-cv-vacation-home-cities',
    title: 'Best Places in Coachella Valley to Buy a Vacation Home',
    category: 'investor-tips',
    city: 'Coachella Valley',
    audiences: ['buyer', 'investor'],
    contentType: 'Investor Tips',
    targetKeyword: 'best Coachella Valley vacation home cities',
    angle: "Comparing CV cities specifically as second-home markets — STR rules, walkability, amenities, price.",
    whyItMatters: "Investor/second-home segment, high intent.",
    researchData: "PS (best STR ecosystem but tight rules), PD (mid-tier), LQ (Old Town walkable), RM (quiet luxury), IW (snowbird).",
  },
  {
    slug: 'top-cv-neighborhoods-appreciation',
    title: 'Top Coachella Valley Neighborhoods for Real Estate Appreciation',
    category: 'market-update',
    city: 'Coachella Valley',
    audiences: ['buyer', 'investor'],
    contentType: 'Market Update',
    targetKeyword: 'best Coachella Valley appreciation neighborhoods',
    angle: "Where homes have appreciated fastest over the last 5-10 years, and where the upside still looks strong.",
    whyItMatters: "Forward-investor SEO.",
    researchData: "Old Las Palmas (historic premium), Movie Colony (MCM premium), La Quinta Cove (entry-level momentum), Cathedral City (gentrification).",
  },
  {
    slug: 'where-are-cv-buyers-coming-from',
    title: 'Where Are Coachella Valley Buyers Coming From?',
    category: 'market-update',
    city: 'Coachella Valley',
    audiences: ['buyer', 'seller'],
    contentType: 'Market Update',
    targetKeyword: 'Coachella Valley buyer origin migration',
    angle: "Migration data — which feeder markets send the most buyers to CV — and what that says about the market.",
    whyItMatters: "Macro market intelligence.",
    researchData: "LA / Orange County / SF Bay / SD primary CA feeders. Out-of-state: WA, OR, CO, AZ. International: Canada. Compare share % over years.",
  },
  {
    slug: 'cv-housing-market-forecast',
    title: 'Coachella Valley Housing Market Forecast',
    category: 'market-update',
    city: 'Coachella Valley',
    audiences: ['buyer', 'seller', 'investor', 'homeowner'],
    contentType: 'Market Update',
    targetKeyword: 'Coachella Valley housing market forecast 2026',
    angle: "Reading the tea leaves — where the CV market is headed next 6-12 months based on inventory, rate trends, and migration data.",
    whyItMatters: "Forecast content has high search volume around year-ends and mid-year.",
    researchData: "Current rate environment, CV inventory levels, demographic tailwinds (retiree migration), STR regulation overhang, climate/insurance risk premium.",
  },
  {
    slug: 'is-now-the-time-to-buy-or-sell-cv',
    title: 'Is Now the Right Time to Buy or Sell in Coachella Valley?',
    category: 'market-update',
    city: 'Coachella Valley',
    audiences: ['buyer', 'seller'],
    contentType: 'Market Update',
    targetKeyword: 'right time buy sell Coachella Valley',
    angle: "Different answer for buyers vs sellers, different answer by season, different answer by city. Honest take.",
    whyItMatters: "Highly searched evergreen with clear lead-gen tie.",
    researchData: "Buyer perspective: summer is the deal window, winter is the competition window. Seller perspective: list in November for snowbird peak, finish before April festival distraction. Note rate environment.",
  },
]

export const ALL_EVERGREEN_SEEDS: EvergreenSeed[] = [
  ...PALM_SPRINGS_LIFESTYLE,
  ...BUYER_INVESTOR_GUIDES,
  ...LUXURY_CONTENT,
  ...HISTORY_DEEPDIVES,
  ...COACHELLA_VALLEY_GUIDES,
  ...RANCHO_MIRAGE,
  ...INDIAN_WELLS,
  ...DEVELOPMENT_PROJECTS,
  ...LIFESTYLE,
  ...MARKET_ANALYSIS,
]

const AUDIENCE_TO_CATEGORY_SCORE: Record<string, number> = {
  'community': 14,
  'market-update': 13,
  'investor-tips': 13,
  'seller-tips': 12,
  'trending-topics': 12,
  'local-history': 11,
  'local-interest': 11,
}

export async function seedEvergreenContentIdeas(): Promise<number> {
  let saved = 0
  for (const seed of ALL_EVERGREEN_SEEDS) {
    // Stable ID — once Shana picks an idea it's marked approved and never
    // re-appears (the menu naturally shrinks as content is produced).
    const id = `evergreen-${seed.slug}`
    const existing = await getIdea(id)
    if (existing) continue   // already in store, don't overwrite

    const audienceValue = AUDIENCE_TO_CATEGORY_SCORE[seed.category] ?? 12
    const idea: IdeaCandidate = {
      id,
      weekId: 'evergreen',
      source: 'internal',
      title: seed.title,
      angle: seed.angle,
      whyItMatters: seed.whyItMatters,
      category: seed.category,
      audiences: seed.audiences,
      contentType: seed.contentType,
      urgency: 'evergreen',
      score: {
        total: 72,
        localRelevance: 23,
        timeliness: 6,
        formatFit: 13,
        audienceValue,
        sourceCredibility: 9,
        novelty: 6,
        seoPotential: 5,
      },
      sourceUrls: [],
      sourceDomains: [],
      sourceLabels: ['Curated — Client Suggestions'],
      researchData: seed.researchData,
      targetKeyword: seed.targetKeyword,
      cityTarget: seed.city,
      status: 'pending',
      createdAt: new Date().toISOString(),
    }
    await saveIdea(idea)
    saved++
  }
  return saved
}
